name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_stable:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
    - name: Docs
      run: cargo doc --verbose --all
  
  build_beta:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --all
    - uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --verbose --all

  build_nightly:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --all
    - uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --verbose --all
      
  check_big_endian:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: powerpc64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose --lib --bins --tests
